# Schema for the configuration files of the Instagram Hashtag Feed module.

instagram_hashtag_feed.settings:
  type: config_object
  label: 'Instagram Hashtag Feed settings'
  mapping:
    instagram_post_auto_publish:
      type: integer
      label: 'Auto publish instagram posts'
